package com.gmail.gerbencdg.mygoalsassistant.data.room

import androidx.lifecycle.LiveData
import androidx.room.Dao
import androidx.room.Insert
import androidx.room.OnConflictStrategy
import androidx.room.Query
import com.gmail.gerbencdg.mygoalsassistant.model.entities.GoalResult
import com.gmail.gerbencdg.mygoalsassistant.utils.DateUtils

@Dao
interface GoalResultDao {

    @Query("SELECT * FROM goal_result WHERE goal_id IS :goalId AND date IS :date")
    fun getGoalResultOfToday(goalId: Int, date: Long = DateUtils.atStartOfDay()): LiveData<GoalResult>

    @Query("SELECT * FROM goal_result WHERE goal_id IS :goalId AND date IS :date")
    fun getNullableGoalResultOfToday(goalId: Int, date: Long = DateUtils.atStartOfDay()) : GoalResult?

    // @Insert(onConflict = OnConflictStrategy.ABORT) Ids are autogenerated, so has no effect
    // fun insertEmptyResultForToday(goalResult: GoalResult)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun insertResults(goals: List<GoalResult>)

    @Insert(onConflict = OnConflictStrategy.REPLACE)
    fun insertResult(goalResult: GoalResult)
}